### PR TITLE
Fixes array parsing

### PR DESCRIPTION
**Pull request by lightsprint09**
Fix for #51

### CODE REVIEW

**Comment by Nadohs** [comment]
Hi, thanks for submitting this PR and sorry it has taken awhile to get back to you. I will be sure to review it this week.

**Comment by lightsprint09** [comment]
Please take look at the second PR as well

**Comment by lightsprint09** [comment]
hey. Still waiting for review. We understand that you are busy but I think this stops the progress of this repo.

**Comment by matthewcheok** [comment]
LGTM but it could possibly be breaking change so we might want to record this in the README or somewhere visible. I'll let @Nadohs chime in if there are any more comments.

**Comment by lightsprint09** [comment]
I am not sure if this is a breaking change. Because it feels like expected behaviour.

**Pull request merged**
