### PR TITLE
Make JSONDecodable initializer throwable instead of failable

### PR DESCRIPTION
**Pull request by srdanrasic**
@matthewcheok I've forked the library and made JSONDecodable initializer throwable. If you'll ever want to update the official, you can use this PR.

### CODE REVIEW

**Comment by matthewcheok** [comment]
Because this is a breaking change, I'll accept this if we try our best to keep things as backward compatible as possible. I suggest the following:

1) We keep the failable initializer `init?` around by implementing this in the protocol extension. That way users implement `init() throws` and get `init?` for free (this calls `init() throws` internally.)

2) We make the change clear in the README and update the documentation, tests and sample code to reflect this change.

Thanks for your PR!

**Comment by srdanrasic** [comment]
Ok, let me do some updates. We will not be able to have both

``` swift
init?(JSONDictionary: JSONObject)
init(JSONDictionary: JSONObject) throws
```

because it causes conflict. If I rename the argument, it works.

``` swift
init(object: JSONObject) throws
```

**Comment by raylillywhite** [comment]
I like `init(object: JSONObject) throws` better myself, but if you think that the `json` prefix is important Matthew, I'd like to propose that we use `init(jsonObject: JSONObject) throws` instead of `init(JSONObject: JSONObject) throw`. As best I can tell, the Swift standard library breaks from the Obj-c convention of always capitalizing initialisms/acronyms, and instead the entire initialism takes the case that it's first letter would normally have. Some examples I could find in the stdlib:

``` swift
init?(_ utf16: String.UTF16View)
init(utf16CodeUnits: UnsafePointer<unichar>, count: Int)
func writeToURL(url: NSURL, atomically useAuxiliaryFile: Bool, encoding enc: NSStringEncoding) throws
```

**Comment by matthewcheok** [comment]
@srdanrasic The tests seem to failing even after accounting for the API change.

```
RegularTests.swift:37:26: '(JSONDictionary: JSONObject) -> User' is not convertible to '(JSONDictionary: JSONObject) -> User?'
```

Any ideas?

**Pull request merged**
